name: Test

on:
  workflow_dispatch:
  pull_request:
  workflow_call:

env:
  PYTHON_VERSION: "3.11"  # Dockerfileで使用しているPythonのバージョンに合わせる

jobs:
  test:
    name: Test application
    runs-on: ubuntu-latest
    timeout-minutes: 30
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install poetry
        run: |
          pipx install poetry

      - name: Set up python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'poetry'

      - name: Create python environment
        run: |
          poetry env use $(which python3)
          poetry install --no-ansi

      - name: Run pytest
        run: poetry run tox -e py

      - name: Run flake8
        run: poetry run tox -e flake8

      - name: Run format
        run: poetry run tox -e format

      - name: Run mypy
        run: poetry run tox -e mypy
